export declare const loader_color_first: string
export declare const loader_color_fourth: string
export declare const loader_color_second: string
export declare const loader_color_third: string
export declare const loader_size_l: string
export declare const loader_size_m: string
export declare const loader_size_s: string
export declare const loaderIcon: string
export declare const loaderRoot: string
export declare const spin: string
