export declare const arrow: string
export declare const control: string
export declare const disabled: string
export declare const dropdown: string
export declare const focus: string
export declare const item: string
export declare const multiDropdown: string
export declare const selected: string
export declare const selectedValues: string
